repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: make-all
        name: make-all
        entry: bash -c '$SHELL -c "make all"'
        language: system
        always_run: true
        pass_filenames: false
